const
    GAME_SPEED = 80,
    CANVAS_WIDTH = 650,
    CANVAS_HEIGHT = 650,
    HELP_BORDER_X = 100,
    HELP_BORDER_Y = 100,
    HELP_THICKNESS = 15

    BAR_WIDTH = 100,
    BAR_HEIGHT = 15,
    BAR_THICKNESS = 15,
    BAR_COLOR = "#4682b4",
    BAR_SPEED_X = 10,
    BAR_SPEED_Y = 10,
    BARX_POSITION_X = CANVAS_WIDTH / 2 - BAR_WIDTH / 2,
    BARX_POSITION_Y = CANVAS_HEIGHT - BAR_HEIGHT,
    BARY_POSITION_Y = CANVAS_HEIGHT / 2 - BAR_WIDTH / 2,

    BAR_BREAK_X = 200,
    BAR_BREAK_Y = 200,

    BALL_RADIUS = 8,
    BALL_COLOR = "#dc143c",
    BALL_SPEED = 3,
    BALL_ANGLE_SENSITIVE = 80,
    BALL_SPEED_INCREASE = 0.02;

    BRICK_X_ALIGN = 150,
    BRICK_Y_ALIGN = 150,
    BRICK_COLUMN = 10,
    BRICK_ROW = 17,
    BRICK_HEIGHT = 10;